### ISSUE TITLE
可以提供详细的部署与安装流程吗？

### ISSUE THREAD

**Issue by anlia260** [duanguang/react-node-cms#1]
最近也想做个CMS的版本，你的技术栈跟我有很多地方的相同。想学习下，能否给一个详细的部署与环境吗？

**Comment by duanguang** [comment]
node:4.4.7   pm2做进程守护，监控，日志这些，部署的话，sever里面的东西，你改改，直接丢到服务端就好了，然后client, src 里面打包发布出来，如果不做分离。就丢到server 里面。。。分离的话，server和src 部署成两个独立的站点
